# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2010 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Vigilo language team <contact@projet-vigilo.org>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version:  vigilo.connector-metro\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 13:09+0100\n"
"PO-Revision-Date: 2011-03-22 11:14+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/twisted/plugins/vigilo_metro.py:41
msgid ""
"Please set the path to the configuration database generated by VigiConf "
"in the settings.ini."
msgstr ""
"Bitte den Pfad auf die von VigiConf in den settings.ini generierte "
"Konfigurationsdatei einstellen"

#: src/vigilo/connector_metro/nodetorrdtool.py:101
#, python-format
msgid "Host '%(host)s' with datasource '%(ds)s' not found in the configuration !"
msgstr ""
"Host '%(host)s' mit dieser Datenquelle '%(ds)s' nicht in der "
"Konfigurationsdatei gefunden!"

#: src/vigilo/connector_metro/nodetorrdtool.py:122
#, python-format
msgid "RRDtool could not create the file: %(filename)s. Message: %(msg)s"
msgstr ""

#: src/vigilo/connector_metro/nodetorrdtool.py:134
#, python-format
msgid "'%(msgtype)s' is not a valid message type for metrology"
msgstr "'%(msgtype)s' ist kein gültiger Nachrichtentyp für Metrologie"

#: src/vigilo/connector_metro/nodetorrdtool.py:144
#, python-format
msgid "Not a valid performance message (missing '%(tag)s' tag)"
msgstr "Keine gültige perf Nachricht (fehlt '%(tag)s')"

#: src/vigilo/connector_metro/nodetorrdtool.py:152
#, python-format
msgid "Skipping perf update for host %s"
msgstr ""

#: src/vigilo/connector_metro/nodetorrdtool.py:178
#, python-format
msgid "Unable to create the directory '%s'"
msgstr "Das Verzeichnis '%s' kann nicht erstellt werden"

#: src/vigilo/connector_metro/nodetorrdtool.py:254
#, python-format
msgid "RRDtool could not update the file %(filename)s. Message: %(msg)s"
msgstr ""

#: src/vigilo/connector_metro/nodetorrdtool.py:272
msgid "Received signal to reload the configuration"
msgstr "Signal zum erneuten Laden der Konfigurationsdatei erhalten"

#: src/vigilo/connector_metro/rrdtool.py:99
#, python-format
msgid "Unable to start \"%(rrdtool)s\". Make sure the path is correct."
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:102
#, python-format
msgid ""
"Unable to start \"%(rrdtool)s\". Make sure RRDtool is installed and you "
"have permissions to use it."
msgstr ""
"\"%(rrdtool)s\" kann nicht gestartet werden. Überprüfen Sie, dass das "
"RRDtool installiert ist und dass Sie eine Benutzungsberechtigung haben."

#: src/vigilo/connector_metro/rrdtool.py:115
#, python-format
msgid "The RRD directory does not exist: %s"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:124
#, python-format
msgid "Unable to create directory '%(dir)s'"
msgstr "Das Verzeichnis '%(dir)s' kann nicht erstellt werden"

#: src/vigilo/connector_metro/rrdtool.py:128
#, python-format
msgid "Unable to write in the directory '%(dir)s'"
msgstr "In das Verzeichnis '%(dir)s' kann nicht geschrieben werden"

#: src/vigilo/connector_metro/rrdtool.py:193
#, python-format
msgid "Started RRDtool subprocess: pid %(pid)d"
msgstr "RRDtool subprocess: pid %(pid)d gestartet"

#: src/vigilo/connector_metro/rrdtool.py:214
msgid "The process has not yet completed the previous job"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:247
msgid "No deferred available in _handle_result(), this should not happen"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:268
msgid "The RRDTool process exited normally"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:270
#, python-format
msgid ""
"The RRDTool process was terminated abnormally with exit code %(rcode)s "
"and message: %(msg)s"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:277
msgid "Restarting..."
msgstr ""

#: src/vigilo/connector_metro/snmp.py:67
msgid "Connection to the SNMP daemon established"
msgstr ""

#: src/vigilo/connector_metro/snmp.py:135
#, python-format
msgid "Received OID outside my base: %s"
msgstr ""

#: src/vigilo/connector_metro/snmp.py:169
msgid "SNMP to RRDTool gateway started"
msgstr ""

#: src/vigilo/connector_metro/snmp.py:180
msgid "SNMP to RRDTool gateway stopped"
msgstr ""

#: src/vigilo/connector_metro/snmp.py:197
#, python-format
msgid "RRD directory does not exist: %s"
msgstr ""

#: src/vigilo/connector_metro/snmp.py:238
#, python-format
msgid "this does not look like an RRD file path: %s"
msgstr ""

#: src/vigilo/connector_metro/vigiconf_settings.py:48
msgid "No configuration database yet!"
msgstr ""

#~ msgid "Le process n'a pas encore fini le job précédent"
#~ msgstr ""

#~ msgid "No configuration database yet !"
#~ msgstr ""

