# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2010 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Vigilo language team <contact@projet-vigilo.org>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version:  vigilo.connector-metro\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 13:09+0100\n"
"PO-Revision-Date: 2011-08-19 18:23+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/twisted/plugins/vigilo_metro.py:44
msgid ""
"Please set the path to the configuration database generated by VigiConf "
"in the settings.ini."
msgstr ""
"Bitte den Pfad auf die von VigiConf in den settings.ini generierte "
"Konfigurationsdatei einstellen"

#: src/vigilo/connector_metro/nodetorrdtool.py:129
#, python-format
msgid "Host '%(host)s' with datasource '%(ds)s' not found in the configuration !"
msgstr ""
"Host '%(host)s' mit dieser Datenquelle '%(ds)s' nicht in der "
"Konfigurationsdatei gefunden!"

#: src/vigilo/connector_metro/nodetorrdtool.py:150
#, python-format
msgid "RRDtool could not create the file: %(filename)s. Message: %(msg)s"
msgstr ""

#: src/vigilo/connector_metro/nodetorrdtool.py:162
#, python-format
msgid "'%(msgtype)s' is not a valid message type for metrology"
msgstr "'%(msgtype)s' ist kein gültiger Nachrichtentyp für Metrologie"

#: src/vigilo/connector_metro/nodetorrdtool.py:172
#, python-format
msgid "Not a valid performance message (missing '%(tag)s' tag)"
msgstr "Keine gültige perf Nachricht (fehlt '%(tag)s')"

#: src/vigilo/connector_metro/nodetorrdtool.py:180
#, python-format
msgid "Skipping perf update for host %s"
msgstr ""

#: src/vigilo/connector_metro/nodetorrdtool.py:206
#, python-format
msgid "Unable to create the directory '%s'"
msgstr "Das Verzeichnis '%s' kann nicht erstellt werden"

#: src/vigilo/connector_metro/nodetorrdtool.py:290
#, python-format
msgid "RRDtool could not update the file %(filename)s. Message: %(msg)s"
msgstr ""

#: src/vigilo/connector_metro/nodetorrdtool.py:390
msgid "Received signal to reload the configuration"
msgstr "Signal zum erneuten Laden der Konfigurationsdatei erhalten"

#: src/vigilo/connector_metro/rrdtool.py:102
#, python-format
msgid "Unable to start \"%(rrdtool)s\". Make sure the path is correct."
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:105
#, python-format
msgid ""
"Unable to start \"%(rrdtool)s\". Make sure RRDtool is installed and you "
"have permissions to use it."
msgstr ""
"\"%(rrdtool)s\" kann nicht gestartet werden. Überprüfen Sie, dass das "
"RRDtool installiert ist und dass Sie eine Benutzungsberechtigung haben."

#: src/vigilo/connector_metro/rrdtool.py:118
#, python-format
msgid "The RRD directory does not exist: %s"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:127
#, python-format
msgid "Unable to create directory '%(dir)s'"
msgstr "Das Verzeichnis '%(dir)s' kann nicht erstellt werden"

#: src/vigilo/connector_metro/rrdtool.py:131
#, python-format
msgid "Unable to write in the directory '%(dir)s'"
msgstr "In das Verzeichnis '%(dir)s' kann nicht geschrieben werden"

#: src/vigilo/connector_metro/rrdtool.py:196
#, python-format
msgid "Started RRDtool subprocess: pid %(pid)d"
msgstr "RRDtool subprocess: pid %(pid)d gestartet"

#: src/vigilo/connector_metro/rrdtool.py:217
msgid "The process has not yet completed the previous job"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:250
msgid "No deferred available in _handle_result(), this should not happen"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:271
msgid "The RRDTool process exited normally"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:273
#, python-format
msgid ""
"The RRDTool process was terminated abnormally with exit code %(rcode)s "
"and message: %(msg)s"
msgstr ""

#: src/vigilo/connector_metro/rrdtool.py:280
msgid "Restarting..."
msgstr ""

#: src/vigilo/connector_metro/vigiconf_settings.py:51
msgid "No configuration database yet!"
msgstr ""

#~ msgid "Connection to the SNMP daemon established"
#~ msgstr ""

#~ msgid "Received OID outside my base: %s"
#~ msgstr ""

#~ msgid "SNMP to RRDTool gateway started"
#~ msgstr ""

#~ msgid "SNMP to RRDTool gateway stopped"
#~ msgstr ""

#~ msgid "RRD directory does not exist: %s"
#~ msgstr ""

#~ msgid "this does not look like an RRD file path: %s"
#~ msgstr ""

