# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2010 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Vigilo language team <contact@projet-vigilo.org>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version:  vigilo.connector-metro\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 13:09+0100\n"
"PO-Revision-Date: 2010-11-19 13:14+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/connector_metro/main.py:34
msgid ""
"Please set the path to the configuration file generated by VigiConf in "
"the settings.ini."
msgstr ""
"Bitte den Pfad auf die von VigiConf in den settings.ini "
"generierte Konfigurationsdatei einstellen"

#: src/vigilo/connector_metro/nodetorrdtool.py:81
msgid "Connection initialized"
msgstr "Verbindung initialisiert"

#: src/vigilo/connector_metro/nodetorrdtool.py:97
#, python-format
msgid "Unable to create directory '%(dir)s'"
msgstr "Das Verzeichnis '%(dir)s' kann nicht erstellt werden"

#: src/vigilo/connector_metro/nodetorrdtool.py:101
#, python-format
msgid "Unable to write in the directory '%(dir)s'"
msgstr "In das Verzeichnis '%(dir)s' kann nicht geschrieben werden"

#: src/vigilo/connector_metro/nodetorrdtool.py:109
#, python-format
msgid "Started RRDtool subprocess: pid %(pid)d"
msgstr "RRDtool subprocess: pid %(pid)d gestartet"

#: src/vigilo/connector_metro/nodetorrdtool.py:114
#, python-format
msgid ""
"Unable to start \"%(rrdtool)s\". Make sure RRDtool is installed and you "
"have permissions to use it."
msgstr ""
"\"%(rrdtool)s\" kann nicht gestartet werden. Überprüfen Sie, dass "
"das RRDtool installiert ist und dass Sie eine "
"Benutzungsberechtigung haben."

#: src/vigilo/connector_metro/nodetorrdtool.py:122
#, python-format
msgid "RRDtool seemed to exit with return code %(returncode)d, restarting it..."
msgstr ""
"RRDtool schien mit Rückgabecode beendet zu werden %(returncode)d, es "
"wird neu gestartet."

#: src/vigilo/connector_metro/nodetorrdtool.py:150
#, python-format
msgid ""
"RRDtool choked on this command '%(cmd)s' using this file '%(filename)s'. "
"RRDtool replied with: '%(msg)s'"
msgstr ""
"RRDtool blockierte bei diesem Befehl '%(cmd)s' unter Benutzung der "
"Datei '%(filename)s'. RRDtool antwortete mit: '%(msg)s'"

#: src/vigilo/connector_metro/nodetorrdtool.py:188
#, python-format
msgid "Unable to create the directory '%(dir)s'"
msgstr "Das Verzeichnis '%(dir)s' kann nicht erstellt werden"

#: src/vigilo/connector_metro/nodetorrdtool.py:195
#, python-format
msgid ""
"Host '%(host)s' with datasource '%(ds)s' not found in the configuration "
"file (%(fileconf)s) !"
msgstr ""
"Host '%(host)s' mit dieser Datenquelle '%(ds)s' nicht in der "
"Konfigurationsdatei (%(fileconf)s) gefunden!"

#: src/vigilo/connector_metro/nodetorrdtool.py:229
#, python-format
msgid "'%(msgtype)s' is not a valid message type for metrology"
msgstr "'%(msgtype)s' ist kein gültiger Nachrichtentyp für Metrologie"

#: src/vigilo/connector_metro/nodetorrdtool.py:238
#, python-format
msgid "Not a valid performance message (missing '%(tag)s' tag)"
msgstr "Keine gültige perf Nachricht (fehlt '%(tag)s')"

#: src/vigilo/connector_metro/nodetorrdtool.py:260
#, python-format
msgid "Unable to create the directory '%s'"
msgstr "Das Verzeichnis '%s' kann nicht erstellt werden"

#: src/vigilo/connector_metro/nodetorrdtool.py:284
#, python-format
msgid "Chat message to forward: %s"
msgstr "Chat Nachricht zur Weiterleitung: %s"

#: src/vigilo/connector_metro/nodetorrdtool.py:327
msgid "Received signal to reload the configuration file"
msgstr "Signal zum erneuten Laden der Konfigurationsdatei erhalten"

#: src/vigilo/connector_metro/nodetorrdtool.py:332
msgid "Got exception"
msgstr "Ausnahme vorhanden"
