# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Vigilo language team <contact@projet-vigilo.org>, 2010.
#
msgid   ""
msgstr  "Project-Id-Version: vigilo.connector-metro\n"
        "Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
        "POT-Creation-Date: 2010-02-19 09:00+0100\n"
        "PO-Revision-Date: 2010-02-19 09:00+0100\n"
        "Last-Translator: Vigilo language team <contact@projet-vigilo.org>\n"
        "Language-Team: Vigilo language team <contact@projet-vigilo.org>\n"
        "MIME-Version: 1.0\n"
        "Content-Type: text/plain; charset=UTF-8\n"
        "Content-Transfer-Encoding: 8bit\n"

#: src/vigilo/connector_metro/nodetorrdtool.py:49
msgid   "Got exception"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:70
msgid   "Connection initialized"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:81
#, python-format
msgid   "Unable to create directory '%(dir)s'"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:85
#, python-format
msgid   "Unable to write in the directory '%(dir)s'"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:93
#, python-format
msgid   "started rrdtool subprocess: pid %(pid)d"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:98
#, python-format
msgid   "Unable to start \"%(rrdtool)s\". Make sure RRDtool is installed and "
        "you have permissions to use it."
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:106
#, python-format
msgid   "RRDtool seemed to exit with return code %(returncode)d, restarting "
        "it..."
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:134
#, python-format
msgid   "'RRDtool send back Error message on this command'%(cmd)s' with this "
        "file '%(filename)s'. RRDtool replied with: '%(msg)s'"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:161
#, python-format
msgid   "Unable to create the directory '%(dir)s'"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:167
#, python-format
msgid   "Host with this datasource '%(host_ds)s' not found in the "
        "configuration file (%(fileconf)s) !"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:197
#, python-format
msgid   "'%(msgtype)s' is not a valid message type for metrology"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:209
#, python-format
msgid   "not a valid perf message (%(i)s is missing '%(perfmsg)s')"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:224
#, python-format
msgid   "Unable to create the directory '%s'"
msgstr  ""

#: src/vigilo/connector_metro/nodetorrdtool.py:247
#, python-format
msgid   "Chat message to forward: %s"
msgstr  ""

#: src/vigilo/connector_metro/main.py:35
msgid "Please set the path to the configuration "
"file generated by Vigiconf in the settings.ini."
msgstr  ""
